// Ferramentas de edição visíveis somente à conta proprietária.
import {initializeApp,getApps,getApp} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
const app=getApps().length?getApp():initializeApp({apiKey:"AIzaSyA-Ti0SOVjh0s8_8rh6SIrP1A9WHYSo6Rs",authDomain:"freefas-d0a9e.firebaseapp.com",projectId:"freefas-d0a9e",appId:"1:251003895899:web:083e03360c682217853f7e",messagingSenderId:"251003895899"});
const owner='zslxVPC5TOhFVefTSGqYAxjI6Xi1';
const auth=getAuth(app);
const css=document.createElement('style');css.textContent='.fb-editor-bar{position:fixed;z-index:99990;bottom:18px;right:16px;display:flex;gap:8px;padding:9px;background:#15181df2;border:1px solid #ffb00077;border-radius:14px;box-shadow:0 8px 25px #0009}.fb-editor-bar a,.fb-inline-edit{display:inline-block;background:#ffb000;color:#141414!important;border-radius:9px;padding:10px 14px;font-weight:800;text-decoration:none!important;font-size:13px}.fb-inline-edit{margin:12px 0}.fb-editor-bar a:focus-visible,.fb-inline-edit:focus-visible{outline:3px solid #fff}';document.head.append(css);
let bar=null;
function addInlineLinks(){document.querySelectorAll('a[href*="materia.html?id="]').forEach(a=>{if(a.dataset.fbEditorAttached)return;const u=new URL(a.href,location.href);if(u.pathname.split('/').pop()!=='materia.html')return;const id=u.searchParams.get('id');if(!id)return;a.dataset.fbEditorAttached='1';const edit=document.createElement('a');edit.className='fb-inline-edit';edit.href='painel-editorial.html?edit='+encodeURIComponent(id);edit.textContent='✎ Editar notícia';edit.setAttribute('aria-label','Editar notícia '+id);a.insertAdjacentElement('afterend',edit)});const article=document.getElementById('editorial-article');if(article&&!article.querySelector('.fb-inline-edit')){const id=new URLSearchParams(location.search).get('id');if(id){const edit=document.createElement('a');edit.className='fb-inline-edit';edit.href='painel-editorial.html?edit='+encodeURIComponent(id);edit.textContent='✎ Editar esta matéria';article.prepend(edit)}}}
onAuthStateChanged(auth,user=>{if(bar){bar.remove();bar=null}document.querySelectorAll('.fb-inline-edit').forEach(x=>x.remove());document.querySelectorAll('[data-fb-editor-attached]').forEach(x=>delete x.dataset.fbEditorAttached);if(!user||user.uid!==owner)return;bar=document.createElement('nav');bar.className='fb-editor-bar';bar.setAttribute('aria-label','Ferramentas do proprietário');bar.innerHTML='<a href="painel-editorial.html">✎ Painel do dono</a>';document.body.append(bar);addInlineLinks();const observer=new MutationObserver(()=>{observer.disconnect();addInlineLinks();observer.observe(document.body,{childList:true,subtree:true})});observer.observe(document.body,{childList:true,subtree:true})});
