const menuBtn=document.querySelector('#menuBtn');const nav=document.querySelector('#nav');
if(nav&&!nav.querySelector('a[href="ferramentas.html"]')){const toolsLink=document.createElement('a');toolsLink.href='ferramentas.html';toolsLink.textContent='Ferramentas';const community=nav.querySelector('a[href="comunidade.html"]');nav.insertBefore(toolsLink,community)}if(nav&&!nav.querySelector('a[href="ajuda.html"]')){const helpLink=document.createElement('a');helpLink.href='ajuda.html';helpLink.textContent='Ajuda';nav.appendChild(helpLink)}
if(menuBtn&&nav){menuBtn.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}));document.addEventListener('click',e=>{if(nav.classList.contains('open')&&!nav.contains(e.target)&&e.target!==menuBtn){nav.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}})}
const current=(location.pathname.split('/').pop()||'index.html').toLowerCase();document.querySelectorAll('#nav a').forEach(a=>{if((a.getAttribute('href')||'').toLowerCase()===current)a.classList.add('active')});
async function shareArticle(){const data={title:document.title,text:'Veja esta matéria no FRIFAS BRASIL',url:location.href};if(navigator.share){try{await navigator.share(data)}catch(e){}}else{try{await navigator.clipboard.writeText(location.href);alert('Link copiado!')}catch(e){alert(location.href)}}}
async function copyText(value,status){try{await navigator.clipboard.writeText(value);if(status)status.textContent='Copiado!'}catch(e){if(status)status.textContent='Não foi possível copiar automaticamente.'}}
function generateNick(){const input=document.querySelector('#nickBase');const out=document.querySelector('#nickOutput');if(!input||!out)return;const base=(input.value||'').trim();if(!base){out.textContent='Digite um nome para começar.';return}const variants=['亗'+base+'亗',base+'ツ','么'+base+'么',base+'メ','『'+base+'』'];out.innerHTML=variants.map(v=>'<button type="button" class="copyChoice" data-copy="'+v.replace(/"/g,'&quot;')+'">'+v+'</button>').join('');out.querySelectorAll('.copyChoice').forEach(b=>b.addEventListener('click',()=>copyText(b.dataset.copy,b)))}
function generateBio(){const input=document.querySelector('#bioBase');const out=document.querySelector('#bioOutput');if(!input||!out)return;const base=(input.value||'').trim()||'Jogador';const bios=['⚡ '+base+' • foco no capa','🔥 '+base+' | só progresso','🎯 '+base+' • jogando do meu jeito'];out.innerHTML=bios.map(v=>'<button type="button" class="copyChoice" data-copy="'+v.replace(/"/g,'&quot;')+'">'+v+'</button>').join('');out.querySelectorAll('.copyChoice').forEach(b=>b.addEventListener('click',()=>copyText(b.dataset.copy,b)))}
function copyInvisible(){const status=document.querySelector('#invisibleStatus');copyText('ㅤ',status)}
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const items=document.querySelectorAll('.reveal');if(reduced||!('IntersectionObserver'in window)){items.forEach(el=>el.classList.add('visible'))}else{const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},{threshold:.12,rootMargin:'0px 0px -4% 0px'});items.forEach(el=>observer.observe(el))}